
dict_cols = {
    "organisationunitname"  : "FOSA",
    "periodname"            : "période",
    "periodcode"            : "Trimestre",
    "QOC-PMA-1.1-Carte sanitaire de l’aire de santé disponible et affichée (format A3 au moins)" : "carte sanitaire",
    "QOC-PMA-1.2-La carte sanitaire comporte les centres d’état civil principaux et secondaires de l’aire de santé": "carte sanitaire et centre d'état civil",
    "QOC-PMA-1.3-Rapports mensuels  (RMA, PEV, PTME PALU, SR,  AVP, CDV, MAPE hebdomadaire, grilles d’évaluation qualité des FOSA par le régulateur)" : "rapports mensuels",
    "QOC-PMA-1.4-Au moins 80 % des recommandations formulées lors de l’évaluation qualité du trimestre dernier ont été appliqués" : " 80 % recommandations qualité",
    "QOC-PMA-1.5-La FOSA a renseigné les données du RMA  pour les 3 derniers mois dans le DHIS 2 du SNIS au moins 80 % des recommandations formulées lors de l’évaluation qualité du trimestre dernier ont été appliqués" : "trois RMA dans DHIS2",
    "QOC-PMA-1.6-Horaire du travail et planning de garde disponible et affiché dans tous les services y compris le bureau du chef de centre": "horaire et planning travail",
    "QOC-PMA-1.7-La FOSA dispose d’un plan de développement d’infrastructure" : "plan d'infrastructures",
    "QOC-PMA-1.8-Procès-verbal des réunions techniques de la FS fait mensuellement et disponible": "PV reunions mensuelles",
    "QOC-PMA-1.9-Fiches de référence vierges disponible (au moins 10)": "fiches de référence",
    "QOC-PMA-1.10-Disponibilité de radio ou téléphone portable": "téléphone portable",
    "QOC-PMA-1.11-Cuisine pour les patients hospitalisés est disponible et propre": "cuisine",
    "QOC-PMA-1.12-Disponibilité d’une morgue/ chambre mortuaire": "morgue",
    "QOC-PMA-2.1-Business plan trimestriel de la FS disponible et accessible": "BP disponible",
    "QOC-PMA-2.2-Plan d’action élaboré avec les acteurs clés": "plan d'action avec acteurs",
    "QOC-PMA-2.3-Rapports mensuels d’analyse de réalisations du business plan": "rapport d'analyse BP",
    "QOC-PMA-2.4-Les cinq problèmes clés du Business Plan du trimestre dernier ont été réalisés à au moins 80%": " 80 % des 5 problèmes clés",
    "QOC-PMA-3.1-Documents financiers et comptables disponibles et bien tenus":"documents financiers bien tenus",
    "QOC-PMA-3.2-Le salaire fixe + prime de performance n’est pas supérieure à 60% du TOTAL des recettes de la FS": "revenus inférieur à 60 % recettes",
    "QOC-PMA-3.3-Système établi du calcul mensuel des primes de performance et connu par le personnel":"critères de primes connus de tous",
    "QOC-PMA-4.1-Clôture disponible et bien entretenu": "clôture disponible",
    "QOC-PMA-4.2-Disponibilité de poubelle dans la cour": "pou dans la cour",
    "QOC-PMA-4.3-Existence d’un système de tri de déchet appliqué": "tri de déchet",
    "QOC-PMA-4.4-Présence de latrines ou toilettes en nombre suffisant et en bon état avec à proximité un dispositif lave main": "latrines et toilettes suffisantes",
    "QOC-PMA-4.5-Présence de douches en nombre suffisant et en bon état": "douches suffisantes",
    "QOC-PMA-4.6-Incinérateur répondant aux normes et fosse à placenta avec couvercle et dans un enclos" : "incinérateur",
    "QOC-PMA-4.7-Fosse à déchet de matériels non infectés disponibles": "fosse à déchet",
    "QOC-PMA-4.8-Propreté de la cour": "Propreté de la cour",
    "QOC-PMA-4.9-Entretien de la cour": "entretien de la cour",
    "QOC-PMA-4.10-Le personnel stérilise les instruments selon les normes": "sterilisationselon les normes",
    "QOC-PMA-4.11-Conditions d’hygiène assurées dans la salle de soins": "hygiène salle de soins",
    "QOC-PMA-5.1-Bonnes conditions d’attente pour la Consultation Externe": "bonne condition d'attente pour CE",
    "QOC-PMA-5.2-Les tarifs du recouvrement de coût de tous les actes et de tous les services sont affichés à l’extérieur et en salle d’attente": "tarifs affichés",
    "QOC-PMA-5.3-Existence d’un système de triage avec des jetons numérotés à l’accueil" : "système de tri CE",
    "QOC-PMA-5.4-Salle de la Consultation Externe en bon état et propre": "salle de CE en bon état",
    "QOC-PMA-5.5-Salle de la CE et l’espace d’attente séparés assurant la confidentialité": "confidentialité de la CE",
    "QOC-PMA-5.6-Salle de la CE et / ou d’urgence éclairée pendant la nuit": "salle de CE éclairée",
    "QOC-PMA-5.7-Toutes les CE sont faites par un infirmier qualifié (au moins IDE)": "CE par IDE",
    "QOC-PMA-5.8-Le personnel est en tenue conforme": "tenue conforme",
    "QOC-PMA-5.9-La numérotation mensuelle correcte dans le registre de CE": "registre numéroté",
    "QOC-PMA-5.10-Disponibilité de services 7 / 7 jours et 24h/24": "service 7 sur 24",
    "QOC-PMA-5.11-Protocole affiché sur le mur pour la prise en charge du paludisme": "protocole malaria affiché",
    "QOC-PMA-5.12-La prise en charge correcte du paludisme simple": "PEC correcte paludisme simple",
    "QOC-PMA-5.13-La prise en charge correcte du paludisme grave": "PEC correcte paludisme grave",
    "QOC-PMA-5.14-La prise en charge correcte des Infection Respiratoire Aigue (IRA)" : "PEC correcte IRA",
    "QOC-PMA-5.15-La prise en charge correcte de la diarrhée": "PEC correcte diarrhée",
    "QOC-PMA-5.16-La proportion de malades traités avec des antibiotiques < 50%": "proportion d'antibiotique inférie à 50 %",
    "QOC-PMA-5.17-La recherche de la Tuberculose (TBC) chez les tousseurs chroniques": "recherche TB",
    "QOC-PMA-5.18-Elaboration de courbes d’évolution en couverture contraceptive, vaccinale, consultation curative et à jour et affichée sur le mur": "courbe contraceptive vaccinale et curative affichée",
    "QOC-PMA-5.19-Disponibilité de stéthoscope / tensiomètre fonctionnel en salle de consultation externe": "stethoscope et tensiomètre",
    "QOC-PMA-5.20-Disponibilité de thermomètre fonctionnel en salle de consultation externe": "thermomètre",
    "QOC-PMA-5.21-Disponibilité d’otoscope auriculaires en salle de CE": "otoscope",
    "QOC-PMA-5.22-Disponibilité d’un pèse bébé en bon état et fonctionnel en salle de CE": "pèse bébé",
    "QOC-PMA-5.23-Lit d’examen disponible (métallique) avec matelas et toile cirée non déchirée": "lit d'examen",
    "QOC-PMA-5.24-Disponibilité d’un pèse personne fonctionnel": "pèse personne",
    "QOC-PMA-5.25-Disponibilité d’abaisse langue": "abaisse langue",
    "QOC-PMA-5.26-Recherche et investigation des maladies sous surveillance": "investigation de maladies sous surveillance",
    "QOC-PMA-5.27-Disponibilité d'une toise en bon état (bien lisible)": "toise",
    "QOC-PMA-5.28-Disponibilité des tables de rapport Poids/Taille en salle de CE": "table poids taille",
    "QOC-PMA-5.29-Détermination de l'état nutritionnel de tous les enfants de moins de 5 ans qui viennent en consultation et en vaccination": "détermination systématique malnutrition chez les enfants",
    "QOC-PMA-6.1-Toutes les consultations PF sont faites par un infirmier IDE au minimum formé en PF complet": "CE par IDE",
    "QOC-PMA-6.2-Local propre disponible garantissant la confidentialité": "local PF propre",
    "QOC-PMA-6.3-Affiche murale ou boite à image avec les méthodes PF disponible dans la salle pour la démonstration": "affiche mûrale et boîte à image",
    "QOC-PMA-6.4-Plan d’action contient une stratégie de couverture Planification Familiale pertinente, relatif à l’amélioration de l’offre et la promotion de la demande" :"plan d'action PF",
    "QOC-PMA-6.5-Stocks de sécurité des intrants contraceptifs ( DMPA en IM et S/cutané et pilules) disponibles": "stocks intrants PF disponibles",
    "QOC-PMA-6.6-Méthodes DIU disponibles et personnel capable de les placer": "DIU disponibles et utilisés",
    "QOC-PMA-6.7-Méthodes Implants disponibles et personnel capable de les insérer et retirer": "implants disponibles et utilisés",
    "QOC-PMA-6.8-Condom disponibles (masculin et féminin)": "condoms disponibles",
    "QOC-PMA-6.9-Registre de la PF disponible et bien rempli (à jour et rempli à toutes les rubriques) sur les 3 derniers mois sans surcharge": "registre PF bien rempli",
    "QOC-PMA-6.10-Fiche de la PF disponible et bien remplie sans surcharge": "fiche PF disponible",
    "QOC-PMA-6.11-Les tarifs du recouvrement de coût pour les contraceptifs et les services de PF sont affichés dans la salle de PF au moins": "tarifs contraceptifs",
    "QOC-PMA-7.1-Laborantin d’au moins niveau ATMS disponible": "ATMS disponible",
    "QOC-PMA-7.10-Présence d’au moins 10 tests de grossesse dans la FOSA.": "tests de grossesse",
    "QOC-PMA-7.2-Le laboratoire est fonctionnel tous les jours de la semaine": "labo 7 sur 7",
    "QOC-PMA-7.3-Résultats enregistrés correctement dans le registre du laboratoire": "registre labo bien rempli",
    "QOC-PMA-7.4-Liste des examens possibles affichée dans le laboratoire": "liste examens affichés",
    "QOC-PMA-7.5-Disponibilité des démonstrations des formes des parasites": "demonstrations des parasites disponibles",
    "QOC-PMA-7.6-Disponibilité d’un microscope fonctionnel": "microscope fonctionnel",
    "QOC-PMA-7.7-Disponibilité d’une centrifugeuse fonctionnelle": "centrifugeuse fonctionnelle",
    "QOC-PMA-7.8-Environnement : propreté de la table de coloration, de prélèvement et du laboratoire en général": "labo propre",
    "QOC-PMA-7.9-Personnel plonge les lames et pipettes souillés dans un récipient contenant une solution de décontamination (protocole affiché)": "protocole de décontamination affiché",
    "QOC-PMA-7.10-Présence d’au moins 10 tests de grossesse dans la FOSA.": "tests de grossesse labo",
    "QOC-PMA-8.1-Equipements disponibles propre et en bon état": "équipements lits matelas disponibles",
    "QOC-PMA-8.2-Bonnes conditions d’hygiène": "hygiène en salle d'hospitalisation",
    "QOC-PMA-8.3-Salle d’hospitalisation éclairée pendant la nuit": "salle d'hospitalisation éclairée",
    "QOC-PMA-8.4-Confidentialité assurée": "confidentialité en salle d'hospitalisation",
    "QOC-PMA-8.5-Registre(s) d’hospitalisation(s) disponible et bien rempli sans surcharge, numéroté et clôturé à la fin de chaque mois":"registre d'hospi tenus",
    "QOC-PMA-8.6-Fiches d’hospitalisation disponibles et bien remplies selon les normes et techniques de gestion": "fiche d'hospitalisation",
    "QOC-PMA-9.1-Le stock de la pharmacie est constitué d’au moins de 90% de médicaments essentiels génériques de la liste des médicaments essentiels de son niveau": "90 % des medicaments essentiels",
    "QOC-PMA-9.2-Personnel tient les outils de gestion des médicaments":"outils de gestion des médicaments tenus",
    "QOC-PMA-9.3-La formation sanitaire s’approvisionne auprès des établissements pharmaceutiques ou de vente en gros figurant dans la liste nationale actualisée": "approvisionnement auprès de structures agrées",
    "QOC-PMA-9.4-Les médicaments sont gardés correctement":"médicaments bien conservés",
    "QOC-PMA-9.5-La pharmacie dépôt livre journalièrement les médicaments selon la réquisition du service de distribution des médicaments":"distribution des médicaments adéquate dans les services",
    "QOC-PMA-9.6-Absence médicaments périmés ou avec des étiquettes falsifiées": "absence de médicaments périmés ou falsifiés",
    "QOC-PMA-9.7-Lieu de distribution de médicaments": "lieu de distribution de médicaments adéquat",
    "QOC-PMA-9.8-Pharmacie tenue par au moins un commis de pharmacie formé ou un technicien en pharmacie ou un pharmacien": "commis formé",

    "QOC-PMA-10.1-Amoxicilline caps /comp 500 mg": "Amoxicilline 500 comp",
    "QOC-PMA-10.2-Amoxicilline sirop 250 mg/ 5ml": "Amoxicilline sirop",
    "QOC-PMA-10.3-Artesunate comp 50 mg – amodiaquine 135 mg ou AL": "amodiaquine Artesunate",
    "QOC-PMA-10.4-Cotrimoxazole comp 480 mg": "cotrimoxazole 480",
    "QOC-PMA-10.5-Diazepam 10 mg / 2ml – injectable":" Diazepam",
    "QOC-PMA-10.6-Fer – acide folique 200 mg + 25 mg": "fefol",
    "QOC-PMA-10.7-Mebendazole comp 100 mg": "Mebendazole",
    "QOC-PMA-10.8-Methergine/syntocinone amp 10 Unités": "ocytocine",
    "QOC-PMA-10.9-Métronidazole comp 250 mg": "Métronidazole 250",
    "QOC-PMA-10.10-Paracétamol comp 500 mg": "Paracétamol",
    "QOC-PMA-10.11-Artésunate injectable/Quinine comp et quinine injectable":"artesunate et quinine injectable",
    "QOC-PMA-10.12-SRO / oral sachet": "SRO",
    "QOC-PMA-10.13-Gants stériles": " Gants stériles",
    "QOC-PMA-10.14-Compresses stériles": "compresses",
    "QOC-PMA-10.15-Solutés glucosé 5%":"glucosé",

    "QOC-PMA-11.1-L’eau suffisante avec savon dans la salle d’accouchement":"eau dans salle d'accouchement",
    "QOC-PMA-11.2-Salle d’accouchement éclairée":"salle d'accouchement éclairée",
    "QOC-PMA-11.3-Déchets collectés correctement dans la salle d’accouchement": "déchets collecté dans salle d'accouchement",
    "QOC-PMA-11.4-Salle d’Accouchement en bon étatt": "salle d'accouchement en bon état",
    "QOC-PMA-11.5-Disponibilité du partogramme": "partogramme",
    "QOC-PMA-11.6-Partogrammes correctement remplis":"partogramme bien tenu",
    "QOC-PMA-11.7-Tous les accouchements effectués par un personnel qualifié (au moins IBA)":" accouchements par personnel qualifié",
    "QOC-PMA-11.8-Disponibilité d’une toise d’un stéthoscope obstétrical, mètre ruban,":"toise en salle d'accouchement",
    "QOC-PMA-11.9-Disponibilité d’une ventouse obstétricale fonctionnelle":"ventouse",
    "QOC-PMA-11.10-Disponibilité d’une seringue d’AMNIO fonctionnelle":"seringue AMNIO",
    "QOC-PMA-11.11-Disponibilité des gants médicaux stériles.":"gants steriles en SA",
    "QOC-PMA-11.12-Disponibilité d’au moins 2 boites d’accouchement stérilisées":"2 boîtes d'accouchement",
    "QOC-PMA-11.13-Disponibilité de deux boites d’épisiotomie dont une stérile":"2 boîtes d'épisiotomie",
    "QOC-PMA-11.14-Table d’accouchement en bon état":"table d'accouchement",
    "QOC-PMA-11.15-Disponibilité d’un pèse bébé fonctionnel":"pèse bébé en SA",
    "QOC-PMA-11.16-Matériel disponible pour les soins aux nouveaux nés":"matériels pour nouveau né",
    "QOC-PMA-11.17-Seau ou bassin à linge souillé disponible":"seau à ling en SA",
    "QOC-PMA-11.18-Disponibilité de moustiquaires dans la salle d’hospitalisation": "moustiquaires en salle d'hospitalisation",
    "QOC-PMA-11.19-Lits avec matelas et literie en bon état dans la salle d’hospitalisation":"matelas et literie en bon état en salle d'hospitalisation",
    "QOC-PMA-11.20-Salle de travail adéquate":"salle de travail adéquat",
    "QOC-PMA-11.21-Surveillance du Postpartum immédiat (des 6 H )":"surveillance Postpartum",
    "QOC-PMA-11.22-Registre d’accouchement disponible et bien rempli sur les 3 derniers mois":"registre d'accouchement",
    "QOC-PMA-11.23-Les tarifs du recouvrement de coût pour les soins obstétricaux sont affichés":"tarifs soins obstétricaux",

    "QOC-PMA-12.1-Salle pour la petite chirurgie disponible et en bon état":"salle de petite chirurgie adéquate",
    "QOC-PMA-12.2-Lit d’examen disponible":"lit d'examen en petite chirurgie",
    "QOC-PMA-12.3-Equipement de base disponible dans la salle": "équipement de base en petite chirurgie",
    "QOC-PMA-12.4-Registre de petite chirurgie bien rempli et à jour":"registre de petite chirurgie tenue",
    "QOC-PMA-12.5-Conditions d’hygiène assurées dans la salle de petite chirurgie":"hygiène en petite chirurgie",




    "QOC-PMA-14.1-Chaine du froid - contrôle régulier de la chaîne de froid et thermomètre présent dans le compartiment du réfrigérateur":"chaîne du froid ace thermomètre",
    "QOC-PMA-14.10-Registre de PEV bien rempli – ou système de fiches disponible":"registre PEV",
    "QOC-PMA-14.11-onnes conditions d’attente pour la CPN et la vaccination": "conditions d'attente adéquates pour PEV",
    "QOC-PMA-14.12-Remise de jetons numérotés selon l’ordre d’arrivée":"jetons au PEV",
    "QOC-PMA-14.13-Disponibilité d’une balance (pèse bébé) en bon état":"pèse bébé au PEV",

    "QOC-PMA-14.14-Planning de vaccination disponible et affiché":"planning PEV",

    "QOC-PMA-14.15-Au moins 90% des séances de vaccination planifiées sur la période ont été réalisées":"90 % de séance PEV réalisées",
    "QOC-PMA-14.16-Une liste de perdus de vue incluant les contacts et la localisation des parents est produite chaque mois et remise au relais communautaire pour rattrapage": "liste de PDV PEV",
    "QOC-PMA-14.2-Le responsable de la FOSA connaît calculer ses besoins mensuels en vaccins et intrants": "besoins en vaccins connus",

    "QOC-PMA-14.3-Disponibilité des différents vaccins dans la FOSA":"vaccins disponibles",
    "QOC-PMA-14.4-Les vaccins sont correctement disposés dans le frigo":"vaccins rangés",

    "QOC-PMA-14.5-Etat chaîne de froid Frigo à pétrole/gaz : stock d’au moins 14 L : bouteille à gaz Frigo solaire/électrique : batterie en bon état":"chaîne du froid avec energie",
    "QOC-PMA-14.6-Les accumulateurs de froid sont bien congelés (au moins 6)":"accumulateurs congélés",
    "QOC-PMA-14.7-Existence de seringues":"seringues disponibles au PEV",
    "QOC-PMA-14.8-Les déchets sont collectés dans des poubelles appropriées avec sac poubelle":"déchets dans sacs poubelles au PEV",
    "QOC-PMA-14.9-Stock de carnets ou cartes de croissance PEV & CPS":"carnet de vaccination disponible",



    "QOC-PMA-15.1-Plan de préparation à l’accouchement disponible et suivis": "plan de préparation à l'accouchement disponibleet suivi",
    "QOC-PMA-15.2-Pèse personne bien réglé à zéro (pèse personne propre pour la CPN)":"pèse personne en CPN",

    "QOC-PMA-15.3-Ruban PB disponible et en bon état (bonne lisibilité)":"ruban disponible en CPN",

    "QOC-PMA-15.4-Détermination de l'état nutritionnel de toute femme en CPN": "détermination de l'état nutritionnel en CPN",
    "QOC-PMA-15.5-Fiche CPN (pour la FS) disponible et bien remplie":"fiche CPN disponible et tenu",
    "QOC-PMA-15.6-Fiche et Registre CPN (pour la FS) montre l’administration de Fer Folate), TPI et VAT":"fiche et registre CPN",
    "QOC-PMA-15.7-Carnet de la CPN (pour la maman) disponible":"carnet CPN disponible",
    "QOC-PMA-15.8-Registre de la CPN disponible et bien rempli": "registre CPN bien tenu",

    "QOC-PMA-16.1-Salle de counseling en bon état":"salle counselling correct",
    "QOC-PMA-16.10-Le service dispose d'une procédure standard pour l'identification et le suivi des nourrissons exposés au VIH, des adultes qui ont manqué leur rendez-vous.":"PDV PVVS",
    "QOC-PMA-16.2-Registre de counseling et dépistage volontaire disponible et bien remplis":"registre dépistage correct",
    "QOC-PMA-16.3-Présence d’une personne formée assurant le counseling en CDV":"personne formée au counselling",
    "QOC-PMA-16.4-Existence de matériel de prélèvement dans le bureau de counseling (en CPN, salle d’accouchement)":"materiels de prélèvement",
    "QOC-PMA-16.5-Conditions d’hygiène assurées dans la salle de counseling":"hygiène en salle de counselling",
    "QOC-PMA-16.6-résence de condom masculin et féminin (au moins 10) et du modèle anatomique":"condoms et modèle anatomique",
    "QOC-PMA-16.7-Stock de sécurité de réactifs disponible":"réactifs disponibles",
    "QOC-PMA-16.8-Le service dispose d'un stock de sécurité pour les ARV adultes (1ère et 2ème lignes), le cotrimoxazole (comprimés et sirop), les ARV pédiatrique,":"staocks ARV et IO",
    "QOC-PMA-16.9-Les registres de traitement anti retro viral existent et sont bien remplis":"registre TAR correct",

    "QOC-PMA-17.1-Existence d’un comité d’identification des indigents fonctionnel":"identification indigents",
    "QOC-PMA-17.2-Les outils du PBF communautaire existe dans la structure":"outils PBF communautaire",
    "QOC-PMA-17.3-Preuve du paiement de la facture des ASC par la FOSA au cours du trimestre":"paiement facture ASC",
    "QOC-PMA-17.4-Il existe la liste des perdues de vue élaborée par la FOSA et remis aux ASC chaque fin du mois":"liste PDV detenus par ASC",
    "QOC-PMA-17.5-Visite à Domicile":"VAD",
    "QOC-PMA-17.6-Effet VAD sur la fréquentation de la structure": "effets VAD sur la structure",

    "QOC-PMA-18.1-Registre de prise en charge de la malnutrition":"registre pec malnutrition",
    "QOC-PMA-18.2-Le personnel du CNA (Centre Nutritionnel en Ambulatoire ) maitrise la prise en charge des malnutris selon programmes de lutte contre la malnutrition":"personnel formé sur la PEC malnutrition",
    "QOC-PMA-18.3-Existence de matériel et des outils d’évaluation du statut nutritionnel fonctionnel":"outils d'évaluation du statut nutritionnel",
    "QOC-PMA-18.4-Conditions d’hygiène assurées dans l’espace dédié au CNAS":"hygiène au CNAS",
    "QOC-PMA-18.5-Présence d’un stock sécurité des intrants de prise en charge de la malnutrition aigüe sévère sans complications":"stocks intrants malnutrition",
    "QOC-PMA-18.6-Respect du protocole de prise en charge de la Malnutrition Aigüe":"respect protocole PEC malnutrition",
    "QOC-PMA-18.7-Absence de publicité sur les substituts du lait maternel (SLM)":"absence publicité substituts du lait maternel",
    "QOC-PMA-18.8-Registre de suivi de la croissance des enfants disponible": "registre suivi croissance des enfants",



    "QOC-PMA-19.1-Information des usagers":"infos état civil aux usagers",
    "QOC-PMA-19.2-Registres de déclaration des faits d’état civil disponibles (naissances décès), bien tenus et à jour":"registre etat civil",
    "QOC-PMA-19.3-Déclaration des naissances":"déclaration naissance",
    "QOC-PMA-19.4-Déclaration de décès":"déclaration décès",
    "QOC-PMA-13.1-Conditions réunies pour le DOTS": "DOTS faisable",
    "QOC-PMA-13.2-Disponibilité d’une Porte lames": "porte lame",
    "QOC-PMA-13.3-Disponibilité d’un crayon diamant":"crayon diamant",
    "QOC-PMA-13.4-Rifampicine-isoniazide-pyrazinamide: cp120+50+300mg - RHZE":"RHZE",
    "QOC-PMA-13.5-Streptomycine 1 gr (en cas d’existence de cas de résistance)":"Streptomycine",
    "QOC-PMA-13.6-Etambutol ou RHE comp 400 mg":"Ethambutol",
    "QOC-PMA-13.7-Crachoirs":"crachoirs",
    "QOC-PMA-13.8-Lames et réactifs disponibles":"lames et réactifs TB"

}


#dict_cols_TB = {}
